### ISSUE TITLE
Please, add support for proto 3

### ISSUE THREAD

**Issue by Igorek536** [consulo/consulo-google-protobuf-old#1]
Hello. Please add support for proto 3. I really like the consulo, but I can not work properly without proto 3 support.

**Comment by VISTALL** [comment]
Hi. Thanks for request. 

I think known where i can get it.

Thanks. Maybe add it at this week

**Comment by VISTALL** [comment]
Hi again. I have check other Proto plugin (https://github.com/protostuff/protobuf-jetbrains-plugin), but i have a couple of controversial issues.

That why - i will implement Proto3 in this plugin.

Can you create different issues for each problems?

Thanks
